// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
///
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2sOkIrUUio2tnZvLEzoByIhKn24CejLA',
    appId: '1:593742643118:web:7ebb4265b84e085bd5123f',
    messagingSenderId: '593742643118',
    projectId: 'firetemp01',
    authDomain: 'firetemp01.firebaseapp.com',
    databaseURL: 'https://firetemp01-default-rtdb.firebaseio.com',
    storageBucket: 'firetemp01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4CESb2tczUug81afi0oP7RlWQdXJwDdU',
    appId: '1:593742643118:android:6223e738d19784d7d5123f',
    messagingSenderId: '593742643118',
    projectId: 'firetemp01',
    databaseURL: 'https://firetemp01-default-rtdb.firebaseio.com',
    storageBucket: 'firetemp01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs3idLiHS3g3irXyuivLsT2iinvp6GoPc',
    appId: '1:593742643118:ios:93b3ef26a1de4232d5123f',
    messagingSenderId: '593742643118',
    projectId: 'firetemp01',
    databaseURL: 'https://firetemp01-default-rtdb.firebaseio.com',
    storageBucket: 'firetemp01.appspot.com',
    iosBundleId: 'com.example.fireTemp01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs3idLiHS3g3irXyuivLsT2iinvp6GoPc',
    appId: '1:593742643118:ios:93b3ef26a1de4232d5123f',
    messagingSenderId: '593742643118',
    projectId: 'firetemp01',
    databaseURL: 'https://firetemp01-default-rtdb.firebaseio.com',
    storageBucket: 'firetemp01.appspot.com',
    iosBundleId: 'com.example.fireTemp01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2sOkIrUUio2tnZvLEzoByIhKn24CejLA',
    appId: '1:593742643118:web:5785b811b1c01151d5123f',
    messagingSenderId: '593742643118',
    projectId: 'firetemp01',
    authDomain: 'firetemp01.firebaseapp.com',
    databaseURL: 'https://firetemp01-default-rtdb.firebaseio.com',
    storageBucket: 'firetemp01.appspot.com',
  );
}
